<div id="shipping-method-additional-load" data-bind="scope:'salectoShippingAdditionalData'" data-mage-init='{"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>}' data-current-shipping-method='<?php echo $this->getCurrentShippingMethod();?>'>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>


<script>
    //<![CDATA[
    requirejs([
        'jquery',
    ], function($){
        if ($.fn.applyBindings != undefined) {
            $('#shipping-method-additional-load').trigger('contentUpdated');
            $('#shipping-method-additional-load').applyBindings();
        }
    });
    //]]>
</script>
